// Run with: node generate-config.js
// Reads MINDMAP_API_BASE_URL from .env and writes a public config.js for the extension.
const fs = require("fs");
const path = require("path");

const envPath = path.join(__dirname, ".env");
const configPath = path.join(__dirname, "config.js");
const defaultApiBaseUrl = "http://localhost:8888";

let apiBaseUrl = defaultApiBaseUrl;

if (fs.existsSync(envPath)) {
  const envContents = fs.readFileSync(envPath, "utf8");
  const match = envContents.match(/^MINDMAP_API_BASE_URL=(.+)$/m);

  if (match) {
    apiBaseUrl = match[1].trim();
  }
}

fs.writeFileSync(
  configPath,
  `// Auto-generated by generate-config.js -- do not commit this file\nconst MINDMAP_API_BASE_URL = "${apiBaseUrl}";\n`,
);

console.log(`config.js written with MINDMAP_API_BASE_URL=${apiBaseUrl}`);
