// Run with: node generate-config.js
// Reads GEMINI_API_KEY from .env and writes config.js for the extension to load
const fs = require("fs");
const path = require("path");

const envPath = path.join(__dirname, ".env");
const configPath = path.join(__dirname, "config.js");

const envContents = fs.readFileSync(envPath, "utf8");
const match = envContents.match(/^GEMINI_API_KEY=(.+)$/m);

if (!match) {
  console.error("GEMINI_API_KEY not found in .env");
  process.exit(1);
}

const key = match[1].trim();

fs.writeFileSync(
  configPath,
  `// Auto-generated by generate-config.js — do not commit this file\nconst GEMINI_API_KEY = "${key}";\n`
);

console.log("config.js written.");
